### ISSUE TITLE
Strange sheet behavior in the example.

### ISSUE THREAD

**Issue by VAndrJ** [felilo/SUICoordinator#32]
In the example, strange behavior is observed:

![Issue example](https://github.com/user-attachments/assets/0e54c34f-1973-49c9-872b-4f30271a0cdb)

Most likely, the problem is in `SheetView`.

## Environment:

Simulator: iOS 18 beta 4.
Device: iOS 18 beta 3.

**Comment by felilo** [comment]
The strange behavior was solved in the version **[V.0.0.72](https://github.com/felilo/SUICoordinator/releases/tag/V.0.0.72)**. Thank you for letting me know
